### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by JackFurby** [GT-Vision-Lab/GuessWhich#5]
Hello,

When trying to start the program I am facing errors saying `sl_evaluate.py` and `rl_evalaute.py` cannot be found, and upon looking for the files they don't seem to be located in the repository. Would it be possible to get hold of these two files or be informed of the set-up instructions I have missed?

**Comment by deshraj** [comment]
Hi @JackFurby, sorry for the inconvenience. It looks like we renamed the files to:
- `[sl_worker.py](https://github.com/GT-Vision-Lab/GuessWhich/blob/master/chatbot/sl_worker.py)`
- `[rl_worker.py](https://github.com/GT-Vision-Lab/GuessWhich/blob/master/chatbot/rl_worker.py)`

I will fix it soon in the codebase.

Thanks!
